[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

#opacity = 1.0
#blur = false

[font]
size = 20.0

#normal.family = "JetBrains Mono"
#bold.family = "JetBrains Mono"
#italic.family = "JetBrains Mono"
#bold_italic.family = "JetBrains Mono"
